export const anatomySystems = [
  {
    id: 'skeletal',
    file: 'skeletal_system.glb',
    name: '骨骼系统',
    english: 'Skeletal System',
    latin: 'Systema skeletale',
    short: '骨骼',
    groups: ['Skeletal_systemg'],
    description:
      '骨骼系统构成人体的支架，保护重要器官，并与关节和肌肉共同完成运动。成人骨骼通常由 206 块骨组成。',
    facts: ['区分中轴骨骼与附肢骨骼', '观察颅骨、脊柱、胸廓和四肢骨', '理解骨性标志与邻近结构关系'],
  },
  {
    id: 'joints',
    file: 'joints.glb',
    name: '关节系统',
    english: 'Articular System',
    latin: 'Systema articulare',
    short: '关节',
    groups: ['Jointsg', 'Skeletal_systemg'],
    referenceGroups: ['Skeletal_systemg'],
    description:
      '关节连接相邻骨骼，并在稳定性与活动度之间取得平衡。模型展示人体主要关节及其空间分布。',
    facts: ['识别人体主要滑膜关节', '比较不同关节的运动轴与活动范围', '理解关节在运动链中的连接作用'],
  },
  {
    id: 'muscular',
    file: 'muscular_syetem.glb',
    name: '肌肉系统',
    english: 'Muscular System',
    latin: 'Systema musculare',
    short: '肌肉',
    groups: ['Muscular_systemg'],
    description:
      '骨骼肌通过收缩产生运动、维持姿势并稳定关节。分层观察有助于理解肌群之间的协同与拮抗关系。',
    facts: ['观察浅层与深层肌群分布', '理解肌肉走向与主要运动功能', '联系肌群、关节与骨骼标志'],
  },
  {
    id: 'insertions',
    file: 'muscelar_insertions.glb',
    name: '肌肉附着点',
    english: 'Muscular Insertions',
    latin: 'Origines et insertiones musculorum',
    short: '附着',
    groups: ['Muscular_systemg', 'Skeletal_systemg'],
    referenceGroups: ['Skeletal_systemg'],
    description:
      '肌肉起点和止点决定其跨越关节的方式与牵拉方向，是分析动作、力矩和功能解剖的重要依据。',
    facts: ['红色表示肌肉起点（Origin）', '蓝色表示肌肉止点（Insertion）', '调低肌肉层透明度可观察附着区域'],
  },
  {
    id: 'cardiovascular',
    file: 'cardiovascular_system.glb',
    name: '心血管系统',
    english: 'Cardiovascular System',
    latin: 'Systema cardiovasculare',
    short: '循环',
    groups: ['Arterial_systemg', 'Venous_systemg'],
    description:
      '心血管系统由心脏与血管网络组成，负责输送氧、营养物质和激素，并带走组织代谢产物。',
    facts: ['追踪体循环与肺循环路径', '区分主要动脉与静脉分支', '观察心脏和大血管的空间位置'],
  },
  {
    id: 'nervous',
    file: 'nervous_system.glb',
    name: '神经系统',
    english: 'Nervous System',
    latin: 'Systema nervosum',
    short: '神经',
    groups: ['Nervous_system_&_Sense_organsg'],
    description:
      '神经系统整合感觉信息、控制运动并协调全身功能，包括中枢神经系统与遍布全身的周围神经。',
    facts: ['区分中枢与周围神经系统', '观察脑、脊髓和主要神经走向', '理解神经分布与身体区域的联系'],
  },
  {
    id: 'visceral',
    file: 'visceral_systems.glb',
    name: '内脏系统',
    english: 'Visceral Systems',
    latin: 'Systemata visceralia',
    short: '内脏',
    groups: ['Visceral_systemsg'],
    description:
      '内脏系统包含消化、呼吸、泌尿与生殖等器官系统。三维视图可直观呈现胸腔、腹腔和盆腔内的器官关系。',
    facts: ['观察主要内脏器官的位置与形态', '理解胸腹盆腔的空间分层', '识别器官之间的毗邻关系'],
  },
  {
    id: 'lymphoid',
    file: 'lymphoid_organs.glb',
    name: '淋巴器官',
    english: 'Lymphoid Organs',
    latin: 'Organa lymphoidea',
    short: '淋巴',
    groups: ['Lymphoid_organsg'],
    description:
      '淋巴器官与淋巴网络参与免疫应答和体液回流。主要结构包括胸腺、脾、淋巴结及相关淋巴组织。',
    facts: ['识别主要淋巴器官', '理解淋巴回流与静脉系统的联系', '观察免疫器官在全身的分布'],
  },
  {
    id: 'regions',
    file: 'Regions_of_human_body.glb',
    name: '全身区域',
    english: 'Body Regions',
    latin: 'Regiones corporis humani',
    short: '全身',
    groups: ['Regions_of_human_bodyg'],
    description:
      '以标准解剖学姿势呈现人体主要区域与体表分区，帮助建立从整体到局部的空间认知，是进入系统解剖学习的基础视图。',
    facts: ['观察人体主要分区与方位关系', '建立头、颈、躯干与四肢的整体定位', '理解标准解剖学姿势与方向术语'],
  },
];
